name: vix-extension
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - flask==2.0.1
    - werkzeug==2.0.3
    - openai==0.28.1
    - python-dotenv==0.19.0
    - flask-cors==3.0.10 
    - playwright==1.44.1